server.port=8080
debug=false
logging.level.web =info
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect.storage_engine=innodb
spring.jpa.properties.lock.timeout=20000
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

spring.datasource.url=jdbc:mysql://actsnf.c1cwgcbagoa7.sa-east-1.rds.amazonaws.com:3306/acnf_loja
spring.datasource.username=root
spring.datasource.password=sSp#$9496m

#configuracao emails
spring.mail.host=mail.acertsis.com.br
spring.mail.port=587
spring.mail.username=teste@acertsis.com.br
spring.mail.password=&N5f=)8S
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.test-connection=true
email.contato=contato@acertsis.com.br
#configuracao boleto
boleto.bb.numeroConvenio=314435
boleto.bb.numeroRefTran=2945979
boleto.bb.numeroRefTranInicial=1000
boleto.bb.beneficiario.nome=Acertsis Desenvolvimento de Sistemas Ltda
boleto.bb.beneficiario.endereco=R General Andrade Neves 90, Sala 02
boleto.bb.beneficiario.endereco.bairro=Centro Historico
boleto.bb.beneficiario.endereco.cidade=Porto Alegre
boleto.bb.beneficiario.endereco.UF=RS
boleto.bb.beneficiario.endereco.cep=90010210
boleto.bb.beneficiario.endereco.pais=Brasil
boleto.bb.beneficiario.cnpj=25135171000159
boleto.bb.msgLoja="Pagavel em qualquer estabelecimento ate a Data de vencimento."
boleto.bb.desabilitar=false
# logging level
logging.level.org.springframework=ERROR
#logging.level.br.com.acertsis=DEBUG
# output to a file
logging.file=app.log
# temp folder example
#logging.file=${java.io.tmpdir}/app.log
logging.pattern.file=%d %p %c{1.} [%t] %m%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
## if no active profile, default is 'default'
spring.profiles.active=prod
# root level
#logging.level.=INFO
#Esta opção desabilita a geracao de boleto e gera um boleto falso

